[package]
name = "agx"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
chrono = { version = "0.4.39", default-features = true }
clap = { version = "4.5.30", features = ["derive"] }
tera = "1.20.0"
toml_edit = "0.22.24"
